name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup golang
              uses: actions/setup-go@v2
              with:
                go-version: '1.21'

            - name: Run tests
              run: |
                go test -v ./...
